version: '2'
services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    volumes:
      - "./db-data:/var/lib/mysql:z"
      - "./db-config:/etc/mysql/conf.d:z"
      - "./db-init:/docker-entrypoint-initdb.d:z"
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
     - 3306:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
     - PMA_ARBITRARY=1
     - PMA_HOST=mariadb
     - PMA_USER=root
    restart: always
    ports:
     - 8080:80
    volumes:
     - /sessions
    links:
     - mariadb
