version: '2'
services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    volumes:
      - "./character.cnf:/etc/mysql/conf.d/character.cnf:z"
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: test
    ports:
     - 3306:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
     - PMA_ARBITRARY=1
     - PMA_HOST=mariadb
     - PMA_USER=root
    restart: always
    ports:
     - 8080:80
    volumes:
     - /sessions
    links:
     - mariadb
